version: "3.3"

services:
  mysql:
    image: mysql
    container_name: mysqldb
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: Wppass
    ports:
      - "3306:3306"
  wordpress:
    depends_on:
      - mysql
    image: wordpress
    container_name: wordpress
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: Wppass
      WORDPRESS_DB_NAME: wpdb

volumes:
  db_data: